# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/engine/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/engine/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/engine/project/CMakeFiles /home/engine/project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/engine/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chessviz

# Build rule for target.
chessviz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chessviz
.PHONY : chessviz

# fast build rule for target.
chessviz/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/build
.PHONY : chessviz/fast

src/chess/board.o: src/chess/board.cpp.o
.PHONY : src/chess/board.o

# target to build an object file
src/chess/board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/board.cpp.o
.PHONY : src/chess/board.cpp.o

src/chess/board.i: src/chess/board.cpp.i
.PHONY : src/chess/board.i

# target to preprocess a source file
src/chess/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/board.cpp.i
.PHONY : src/chess/board.cpp.i

src/chess/board.s: src/chess/board.cpp.s
.PHONY : src/chess/board.s

# target to generate assembly for a file
src/chess/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/board.cpp.s
.PHONY : src/chess/board.cpp.s

src/chess/game.o: src/chess/game.cpp.o
.PHONY : src/chess/game.o

# target to build an object file
src/chess/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/game.cpp.o
.PHONY : src/chess/game.cpp.o

src/chess/game.i: src/chess/game.cpp.i
.PHONY : src/chess/game.i

# target to preprocess a source file
src/chess/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/game.cpp.i
.PHONY : src/chess/game.cpp.i

src/chess/game.s: src/chess/game.cpp.s
.PHONY : src/chess/game.s

# target to generate assembly for a file
src/chess/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/game.cpp.s
.PHONY : src/chess/game.cpp.s

src/chess/rules.o: src/chess/rules.cpp.o
.PHONY : src/chess/rules.o

# target to build an object file
src/chess/rules.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/rules.cpp.o
.PHONY : src/chess/rules.cpp.o

src/chess/rules.i: src/chess/rules.cpp.i
.PHONY : src/chess/rules.i

# target to preprocess a source file
src/chess/rules.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/rules.cpp.i
.PHONY : src/chess/rules.cpp.i

src/chess/rules.s: src/chess/rules.cpp.s
.PHONY : src/chess/rules.s

# target to generate assembly for a file
src/chess/rules.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/chess/rules.cpp.s
.PHONY : src/chess/rules.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ui/board_renderer.o: src/ui/board_renderer.cpp.o
.PHONY : src/ui/board_renderer.o

# target to build an object file
src/ui/board_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/board_renderer.cpp.o
.PHONY : src/ui/board_renderer.cpp.o

src/ui/board_renderer.i: src/ui/board_renderer.cpp.i
.PHONY : src/ui/board_renderer.i

# target to preprocess a source file
src/ui/board_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/board_renderer.cpp.i
.PHONY : src/ui/board_renderer.cpp.i

src/ui/board_renderer.s: src/ui/board_renderer.cpp.s
.PHONY : src/ui/board_renderer.s

# target to generate assembly for a file
src/ui/board_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/board_renderer.cpp.s
.PHONY : src/ui/board_renderer.cpp.s

src/ui/input_handler.o: src/ui/input_handler.cpp.o
.PHONY : src/ui/input_handler.o

# target to build an object file
src/ui/input_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/input_handler.cpp.o
.PHONY : src/ui/input_handler.cpp.o

src/ui/input_handler.i: src/ui/input_handler.cpp.i
.PHONY : src/ui/input_handler.i

# target to preprocess a source file
src/ui/input_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/input_handler.cpp.i
.PHONY : src/ui/input_handler.cpp.i

src/ui/input_handler.s: src/ui/input_handler.cpp.s
.PHONY : src/ui/input_handler.s

# target to generate assembly for a file
src/ui/input_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/input_handler.cpp.s
.PHONY : src/ui/input_handler.cpp.s

src/ui/piece_renderer.o: src/ui/piece_renderer.cpp.o
.PHONY : src/ui/piece_renderer.o

# target to build an object file
src/ui/piece_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/piece_renderer.cpp.o
.PHONY : src/ui/piece_renderer.cpp.o

src/ui/piece_renderer.i: src/ui/piece_renderer.cpp.i
.PHONY : src/ui/piece_renderer.i

# target to preprocess a source file
src/ui/piece_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/piece_renderer.cpp.i
.PHONY : src/ui/piece_renderer.cpp.i

src/ui/piece_renderer.s: src/ui/piece_renderer.cpp.s
.PHONY : src/ui/piece_renderer.s

# target to generate assembly for a file
src/ui/piece_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/piece_renderer.cpp.s
.PHONY : src/ui/piece_renderer.cpp.s

src/ui/window.o: src/ui/window.cpp.o
.PHONY : src/ui/window.o

# target to build an object file
src/ui/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/window.cpp.o
.PHONY : src/ui/window.cpp.o

src/ui/window.i: src/ui/window.cpp.i
.PHONY : src/ui/window.i

# target to preprocess a source file
src/ui/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/window.cpp.i
.PHONY : src/ui/window.cpp.i

src/ui/window.s: src/ui/window.cpp.s
.PHONY : src/ui/window.s

# target to generate assembly for a file
src/ui/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessviz.dir/build.make CMakeFiles/chessviz.dir/src/ui/window.cpp.s
.PHONY : src/ui/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chessviz"
	@echo "... src/chess/board.o"
	@echo "... src/chess/board.i"
	@echo "... src/chess/board.s"
	@echo "... src/chess/game.o"
	@echo "... src/chess/game.i"
	@echo "... src/chess/game.s"
	@echo "... src/chess/rules.o"
	@echo "... src/chess/rules.i"
	@echo "... src/chess/rules.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ui/board_renderer.o"
	@echo "... src/ui/board_renderer.i"
	@echo "... src/ui/board_renderer.s"
	@echo "... src/ui/input_handler.o"
	@echo "... src/ui/input_handler.i"
	@echo "... src/ui/input_handler.s"
	@echo "... src/ui/piece_renderer.o"
	@echo "... src/ui/piece_renderer.i"
	@echo "... src/ui/piece_renderer.s"
	@echo "... src/ui/window.o"
	@echo "... src/ui/window.i"
	@echo "... src/ui/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

